name: pull-request-tests
run-name: ${{ github.actor }} is doing some testing
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm install -g bats
      - run: bats -v
      - run: npm run test
